INSERT INTO burgers (burger_name, devoured) VALUES ("Olive and Let Die Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Poblano Picasso Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Hit Me With Your Best Shallot Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("The Sound and the Curry Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Chorizo Your Own Adventure Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("It's fun to eat at the rYeMCA Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("If Looks Could Kale Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Poutine on the Ritz Burger ", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Summer Thyme Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("To Err Is Cumin Burger", false);